services:
  qpc-server:
    build: .
    environment:
      QPC_DBMS: postgres
      QPC_DBMS_DATABASE: postgres
      QPC_DBMS_HOST: qpc-db
      QPC_DBMS_PASSWORD: qpc
      QPC_DBMS_PORT: 5432
      QPC_DBMS_USER: qpc
      QPC_SERVER_PASSWORD: q1w2e3r4
      QPC_SERVER_TIMEOUT: 5
      QPC_SERVER_USERNAME: admin

    ports:
      - "9443:443"
    volumes:
      - .:/app
      - ./deploy:/deploy
    depends_on:
      - qpc-db
    restart: always

  qpc-db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: qpc
      POSTGRES_PASSWORD: qpc
    ports:
      - 54321:5432
    # Set health checks to wait until postgres has started
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
  scan-target:
    build:
      context: .
      dockerfile: Dockerfile.scan-target