services:
  qpc-server:
    build: .
    environment:
      ANSIBLE_LOG_LEVEL: 3
      QPC_DBMS: postgres
      QPC_DBMS_DATABASE: postgres
      QPC_DBMS_HOST: qpc-db
      QPC_DBMS_PASSWORD: qpc
      QPC_DBMS_PORT: 5432
      QPC_DBMS_USER: qpc
      QPC_SERVER_PASSWORD: q1w2e3r4
      QPC_SERVER_TIMEOUT: 5
      QPC_SERVER_USERNAME: admin

    ports:
      - "9443:443"
    volumes:
      - ./quipucords/secret.txt:/var/data/secret.txt
      - .:/app
      - ./deploy:/deploy
    depends_on:
      - qpc-db
    restart: always

  qpc-db:
    image: registry.redhat.io/rhel8/postgresql-13
    environment:
      POSTGRESQL_USER: qpc
      POSTGRESQL_PASSWORD: qpc
      POSTGRESQL_DATABASE: qpc-db
    ports:
      - 54321:5432
    # Set health checks to wait until postgres has started
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
  scan-target:
    build:
      context: .
      dockerfile: Dockerfile.scan-target
    privileged: true
    ports:
      - 2222:2222
