[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools", 
    "setuptools_scm[toml]",
    "wheel",
]  # PEP 508 specifications.

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"

[tool.darker]
revision = "a362b28db064c7a4ee38fe66685ba891f33ee5ba"
isort = true

[tool.flakeheaven]
base = "https://raw.githubusercontent.com/quipucords/linting/main/base-flakeheaven.toml"
baseline = ".flakeheaven-baseline"

[tool.flakeheaven.exceptions."quipucords/api/migrations/*.py"]
"flake8-*" = [
    "-D100",
    "-D101",
]
pylint = [
    "-C0103", # invalid-name
    "-C0114", # missing-module-docstring
    "-C0115", # missing-class-docstring
]

[tool.black]
target-version = ['py39']

[tool.isort]
profile = "black"
known_first_party = [
    "api",
    "compat",
    "fingerprinter",
    "log_messages",
    "quipucords",
    "scanner",
    "tests",
    "utils",
]

[tool.pylint.basic]
good-names = ["db", "i", "j", "k", "ex", "Run", "_"]

[tool.pylint.master]
init-hook = "import sys; sys.path.append('./quipucords')"
django-settings-module = "quipucords.settings"
load-plugins = [
    "pylint_django",
    "pylint_pytest",
]

[tool.pytest.ini_options]
pythonpath = "quipucords/"
addopts = [
    "--ds=quipucords.settings",
    "--block-network",
    "--allowed-hosts=127.0.0.1,::1",
]
python_files = [
    "tests.py",
    "test_*.py",
    "*_tests.py",
    "tests_*.py",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
    "dbcompat: marks tests using our db compat module."
]