# Generated by Django 4.2.4 on 2023-09-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_detailsreport_sources"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deploymentsreport",
            old_name="report_id",
            new_name="fake_report_id",
        ),
        migrations.RenameField(
            model_name="detailsreport",
            old_name="report_id",
            new_name="fake_report_id",
        ),
        migrations.RenameField(
            model_name="scanjob",
            old_name="report_id",
            new_name="fake_report_id",
        ),
    ]
