# Generated by Django 4.2.4 on 2023-09-20 14:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_rename_report_id_deploymentsreport_fake_report_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_version", models.CharField(max_length=64)),
                ("report_platform_id", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.AddField(
            model_name="deploymentsreport",
            name="report",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.report"
            ),
        ),
        migrations.AddField(
            model_name="detailsreport",
            name="report",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.report"
            ),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="report",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.report"
            ),
        ),
    ]
