# Generated by Django 4.2.4 on 2023-09-20 18:51

from django.db import migrations


def create_reports_for_old_data(apps, schema_editor):
    """Create report model for older reports."""
    DeploymentsReport = apps.get_model("api", "DeploymentsReport")
    Report = apps.get_model("api", "Report")
    for deployments_report in DeploymentsReport.objects.all():
        report = Report.objects.create(
            id=deployments_report.id,
            report_version=deployments_report.report_version,
            report_platform_id=deployments_report.report_platform_id,
        )
        deployments_report.report = report
        deployments_report.save()

        details_report = deployments_report.details_report
        details_report.report = report
        details_report.save()

        scan_job = details_report.scanjob
        scan_job.report = report
        scan_job.save()
    # since we manually set values for report id, restart it's sequence
    max_report_id = Report.objects.latest("id").id
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"ALTER SEQUENCE api_report_id_seq RESTART WITH {max_report_id+1}"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_report_deploymentsreport_report_detailsreport_report_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_reports_for_old_data, reverse_code=migrations.RunPython.noop
        )
    ]
